<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Raspberry Pi on Thomas J. Petz, Jr.</title>
    <link>http://localhost:1313/categories/raspberry-pi/</link>
    <description>Recent content in Raspberry Pi on Thomas J. Petz, Jr.</description>
    <generator>Hugo</generator>
    <language>en-us</language>
    <lastBuildDate>Sun, 05 Apr 2020 10:26:49 -0400</lastBuildDate>
    <atom:link href="http://localhost:1313/categories/raspberry-pi/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Resolution on Bind9 on NFS</title>
      <link>http://localhost:1313/posts/bind9onnfs/</link>
      <pubDate>Sun, 05 Apr 2020 10:26:49 -0400</pubDate>
      <guid>http://localhost:1313/posts/bind9onnfs/</guid>
      <description>&lt;p&gt;After a good bit of investigation and thinkingâ€¦ the problem with bind9 has nothing to do with bind9. The problem was a mismatch between UIDs between the Synology NAS server and the bind account on the pi. As I was using sec=sys for authentication all the authentication is based on UIDs. On the pi bind has a UID of 109. There was no account on my Synology NAS with a UIDs of 109. Hence the access was denied by the NFS server.&lt;/p&gt;</description>
    </item>
  </channel>
</rss>
